local math_ceil, math_floor = math.ceil, math.floor
local table_insert, table_remove, table_concat, string_len = table.insert, table.remove, table.concat, string.len
local client_log, client_color_log = client.log, client.color_log

local to_dump = {
	"client",
	"entity",
	"ui",
    "utils",
	"render",
	"math",
	"table",
    "string",
	"materials"
}

local to_dump_global = {
	"tonumber",
	"tostring",
	"assert",
	"error",
	"pairs",
	"ipairs",
	"next",
	"setmetatable",
	"getmetatable",
	"pcall",
	"type",
	"unpack",
}

local ignore = {
	["string"] = {
		"rep",
		"dump",
		"byte",
		"char",
	},
	["table"] = {
		"maxn",
		"foreach",
		"foreachi",
		"move",
		"getn",
		"pack",
		"unpack"
	},
	["math"] = {
		"log10",
		"randomseed",
		"random",
		"huge",
		"ldexp",
		"frexp",
		"tanh",
		"modf"
	},
}

local ignore_draw = true
local optimize_lookups = false
local split_tables = true
local split_message_length = false

local function table_contains(table, val)
	for i = 1, #table do
		if table[i] == val then
			return true
		end
	end
	return false
end

local function array_split(table, n, start)
	local new_table = {}
	local start = start or 1
	for i=start, n do
		local element = table[i]
		if element ~= nil then
			table_insert(new_table, element)
		end
	end
	return new_table
end

local function array_sub(t1, t2)
  local t = {}
  for i = 1, #t1 do
    t[t1[i]] = true
  end
  for i = #t2, 1, -1 do
    if t[t2[i]] then
      table_remove(t2, i)
    end
  end
end

local function create_local_variables(tbl, name, ignored)
	local part1 = {}
	local part2 = {}

	for key, name_tmp in pairs(tbl) do
		local name = name
		if type(name_tmp) == "string" then
			name = name_tmp
		end
		if not table_contains(ignored, key) and type(key) == "string" then
			if name then
				table_insert(part1, name .. "_" .. key)
				table_insert(part2, name .. "." .. key)
			else
				table_insert(part1, key)
				table_insert(part2, key)
			end
		end
	end

	local message = "local " .. table_concat(part1, ", ") .. " = " .. table_concat(part2, ", ")
	if split_message_length then
		local messages = {}

		local parts = 1
		if message:len() > 400 then
			parts = math_ceil(message:len() / 400)
		end

		local split_at = math_floor(#part1/parts)
		local start = 0

		for i=1, parts do
			local split_at_temp = split_at * i + 2
			local part1_1, part2_1 = array_split(part1, split_at_temp, start+1), array_split(part2, split_at_temp, start+1)
			table_insert(messages, "local " .. table_concat(part1_1, ", ") .. " = " .. table_concat(part2_1, ", "))
			start = split_at_temp
		end
		for i=1, #messages do
			print(messages[i])
		end
	else
		print(message)
	end
end

local function dump_api()
	print("Copy and paste this into your script:")
	print("--local variables for API functions. Generated by using ")

	local tbl = {}

	if split_tables then
		for i=1, #to_dump do
			local name = to_dump[i]
			local tbl = _G[name]
			local ignored = ignore[name] or {}
			if ignore_draw and name == "client" then
				for key, _ in pairs(render) do
					table_insert(ignored, key)
					table_insert(ignored, "draw_" .. key)
				end
			end
			create_local_variables(tbl, name, ignored)
		end
	else
		for i=1, #to_dump do
			local name = to_dump[i]
			local tbl = _G[name]
			local ignored = ignore[name] or {}
			if ignore_draw and name == "client" then
				for key, _ in pairs(renderer) do
					table_insert(ignored, key)
					table_insert(ignored, "draw_" .. key)
				end
			end
		end
	end

	for i=1, #to_dump_global do
		tbl[to_dump_global[i]] = false
	end

	create_local_variables(tbl, nil, {})

	print(182, 231, 23, "--end of local variables")
end

--ui.new_button("MISC", "Lua", "Generate API local variables", dump_api)
ui.find("Skins", "Skins"):button("Generate API local variables")
dump_api()

